# --------------------------------------------------------------------------- #
# Docker Instructions for OpenFOAM v2406                                      #
# --------------------------------------------------------------------------- #
# Author: Jan Gartner                                                         #
#                                                                             # 
# Installs OpenFOAM v2406 in Ubuntu 22.04 LTS                                 #
# --------------------------------------------------------------------------- #

FROM ubuntu:22.04


# Install all required packages 

RUN export DEBIAN_FRONTEND=noninteractive \
 && apt-get update \
 && apt-get install -y \
        build-essential \
        autoconf \
        autotools-dev \
        cmake \
        gawk \
        gnuplot \
        flex \
        libfl-dev \
        libreadline-dev \
        zlib1g-dev \
        openmpi-bin \
        libopenmpi-dev \
        mpi-default-bin \
        mpi-default-dev  \
        libgmp-dev \
        libmpfr-dev \
        libmpc-dev \
        git \
        vim \
        wget \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

ARG UID=1000
ARG GID=1000

# Adapt these settings for other ESI versions 
ENV OF_USER="ofuser"
ENV FOAM_INST_DIR="/home/${OF_USER}/OpenFOAM"
ENV VERSION=v2406
ENV foamDotFile="$FOAM_INST_DIR/OpenFOAM-${VERSION}/etc/bashrc"  


# This has to be done as RUN executes /bin/sh and the 
# source of the OpenFOAM bashrc requires /bin/bash 
RUN rm -f /bin/sh && ln -sT /bin/bash /bin/sh 


# Create a gitlab user and group
# This is required for GitLab CI
RUN groupadd -g $GID "${OF_USER}" \
 && useradd -m -d "/home/${OF_USER}" -r -u $UID -g $GID ${OF_USER}

USER ${OF_USER}

# ----------------------------
# Install OpenFOAM  
# ---------------------------

RUN mkdir -p ${FOAM_INST_DIR}

WORKDIR "${FOAM_INST_DIR}"
RUN git clone https://gitlab.com/openfoam/core/openfoam.git OpenFOAM-${VERSION}\
    && git clone https://gitlab.com/openfoam/core/thirdparty-common.git ThirdParty-${VERSION}


RUN . $foamDotFile \
    && cd ${WM_PROJECT_DIR}                         \
    && git checkout OpenFOAM-${VERSION}             \
    && git submodule init && git submodule update   \
    && . $foamDotFile                               \
    && cd ${WM_THIRD_PARTY_DIR}                     \
    && git checkout ${VERSION}                      \
    && git submodule init && git submodule update   


#============================================================================
#                    Build Third Party Libraries
#============================================================================
WORKDIR "${FOAM_INST_DIR}/ThirdParty-${VERSION}"

RUN . $foamDotFile \
    && cd ${WM_THIRD_PARTY_DIR} \
    && wget http://www.fftw.org/fftw-3.3.10.tar.gz \
    && tar -xzf fftw-3.3.10.tar.gz \
    && ./makeFFTW > log.makeFFTW

RUN . $foamDotFile \
    && cd ${WM_THIRD_PARTY_DIR} \
    && wget https://gforge.inria.fr/frs/download.php/file/38187/scotch_6.1.0.tar.gz \
    && tar -xzf scotch_6.1.0.tar.gz \
    && ./makeSCOTCH > log.makeSCOTCH


#============================================================================
#                    Build OpenFOAM
#============================================================================
WORKDIR "${FOAM_INST_DIR}/OpenFOAM-${VERSION}"

RUN . $foamDotFile \
	&& ./Allwmake -j -k -s -l \
	&& ./Allwmake -l

